import { Vehicle } from '../types';

export const vehicles: Vehicle[] = [
  {
    id: 'hatchback',
    name: 'Hatchback',
    category: ['budget'],
    capacity: '3–4 Passengers',
    luggage: '1–2 Bags',
    ac: true,
    pricePerKm: 10,
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80',
    features: ['AC', 'Music System', 'GPS', 'Compact & Nimble'],
    bestFor: 'City errands, short local trips',
    description: 'Perfect for solo travelers and couples navigating city streets. Fuel efficient and easy to park.',
    destinations: ['Delhi', 'Noida', 'Gurgaon', 'Local City'],
    badge: 'Most Economical',
  },
  {
    id: 'sedan',
    name: 'Sedan',
    category: ['budget', 'family'],
    capacity: '4 Passengers',
    luggage: '2–3 Bags',
    ac: true,
    pricePerKm: 12,
    image: 'https://images.unsplash.com/photo-1617469767280-b6de17e5a13c?w=800&q=80',
    features: ['AC', 'Spacious Boot', 'Comfortable Seats', 'GPS'],
    bestFor: 'City & outstation travel',
    description: 'The most popular choice for families and business travelers alike. Comfortable, reliable, and economical.',
    destinations: ['Jaipur', 'Agra', 'Chandigarh', 'Delhi', 'Haridwar'],
  },
  {
    id: 'premium-sedan',
    name: 'Premium Sedan',
    category: ['luxury'],
    capacity: '4 Passengers',
    luggage: '3 Bags',
    ac: true,
    pricePerKm: 15,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    features: ['AC', 'Leather Seats', 'WiFi', 'Bottled Water', 'Chauffeur'],
    bestFor: 'VIP & corporate travel',
    description: 'Executive-class comfort for business professionals. Leather interiors, tinted windows, and a professional chauffeur.',
    destinations: ['Delhi', 'Chandigarh', 'Jaipur', 'Agra'],
    badge: 'Business Class',
  },
  {
    id: 'compact-suv',
    name: 'Compact SUV',
    category: ['family', 'suv'],
    capacity: '5 Passengers',
    luggage: '3 Bags',
    ac: true,
    pricePerKm: 14,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80',
    features: ['AC', 'Higher Ground Clearance', 'Comfortable Ride', 'GPS'],
    bestFor: 'Family weekend trips',
    description: 'The sweet spot between comfort and capability. Great for families heading out for weekend getaways.',
    destinations: ['Rishikesh', 'Haridwar', 'Mussoorie', 'Nainital'],
  },
  {
    id: 'suv',
    name: 'SUV',
    category: ['family', 'suv'],
    capacity: '6–7 Passengers',
    luggage: '4–5 Bags',
    ac: true,
    pricePerKm: 16,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    features: ['AC', 'Spacious 3rd Row', 'Long-Range Comfort', 'GPS', 'Music System'],
    bestFor: 'Long distance family travel',
    description: 'Command the road with premium space for everyone. Ideal for large families or groups heading on longer journeys.',
    destinations: ['Manali', 'Shimla', 'Nainital', 'Jaipur', 'Agra'],
  },
  {
    id: '4x4-suv',
    name: '4×4 SUV',
    category: ['suv'],
    capacity: '5–7 Passengers',
    luggage: '4 Bags',
    ac: true,
    pricePerKm: 22,
    image: 'https://images.unsplash.com/photo-1614026480418-bd11fdb9fa06?w=800&q=80',
    features: ['4WD', 'AC', 'High Ground Clearance', 'Snow Ready', 'GPS'],
    bestFor: 'Mountains, snow & off-road',
    description: 'Built for the toughest terrain. When roads get steep and snowy, this vehicle conquers where others falter.',
    destinations: ['Manali', 'Leh', 'Kasol', 'Dharamshala', 'Shimla'],
    badge: 'Mountain Ready',
  },
  {
    id: 'muv-mpv',
    name: 'MUV / MPV',
    category: ['family', 'suv'],
    capacity: '6–7 Passengers',
    luggage: '4–5 Bags',
    ac: true,
    pricePerKm: 16,
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80',
    features: ['AC', 'Sliding Doors', 'Flexible Seating', 'Spacious Boot', 'GPS'],
    bestFor: 'Comfortable family travel',
    description: 'Maximum versatility with captain seats and sliding doors. Perfect when comfort and cargo space both matter.',
    destinations: ['Jaipur', 'Agra', 'Chandigarh', 'Delhi', 'Mussoorie'],
  },
  {
    id: 'innova-crysta',
    name: 'Innova Crysta',
    category: ['family', 'suv', 'luxury'],
    capacity: '6–7 Passengers',
    luggage: '5 Bags',
    ac: true,
    pricePerKm: 18,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80',
    features: ['AC', 'Captain Seats', 'Premium Cabin', 'GPS', 'Powerful Engine'],
    bestFor: 'Premium outstation travel',
    description: 'India\'s most trusted outstation vehicle. The Innova Crysta is the gold standard for comfortable long-distance travel.',
    destinations: ['Manali', 'Shimla', 'Nainital', 'Jaipur', 'Agra', 'Haridwar', 'Rishikesh'],
    badge: 'Most Trusted',
  },
  {
    id: 'luxury-car',
    name: 'Luxury Car',
    category: ['luxury'],
    capacity: '4 Passengers',
    luggage: '3 Bags',
    ac: true,
    pricePerKm: 45,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    features: ['Premium AC', 'Leather Seats', 'Minibar', 'Tinted Glass', 'Chauffeur', 'WiFi'],
    bestFor: 'Weddings, VIP & corporate',
    description: 'Arrive in absolute style. Our fleet of luxury vehicles makes every entrance unforgettable — for weddings, events, and top executives.',
    destinations: ['Delhi', 'Chandigarh', 'Jaipur'],
    badge: '⭐ Ultra Premium',
  },
  {
    id: 'tempo-traveller',
    name: 'Tempo Traveller',
    category: ['group'],
    capacity: '10–15 Passengers',
    luggage: '8–10 Bags',
    ac: true,
    pricePerKm: 25,
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80',
    features: ['AC', 'Pushback Seats', 'Music System', 'Large Windows', 'GPS'],
    bestFor: 'Group tours & pilgrimages',
    description: 'The classic choice for medium-sized groups. Comfortable seating with pushback mechanism and panoramic windows.',
    destinations: ['Haridwar', 'Rishikesh', 'Jaipur', 'Agra', 'Manali', 'Shimla'],
  },
  {
    id: 'force-traveller',
    name: 'Force Traveller',
    category: ['group'],
    capacity: '12–17 Passengers',
    luggage: '10–12 Bags',
    ac: true,
    pricePerKm: 28,
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80',
    features: ['AC', 'High Roof', 'More Headroom', 'Luggage Rack', 'GPS'],
    bestFor: 'Larger group trips',
    description: 'More space than a Tempo Traveller with high-roof cabin giving excellent headroom. Great for pilgrimage groups.',
    destinations: ['Haridwar', 'Rishikesh', 'Manali', 'Jaipur'],
  },
  {
    id: 'mini-bus',
    name: 'Mini Bus',
    category: ['buses', 'group'],
    capacity: '20–25 Passengers',
    luggage: '15+ Bags',
    ac: true,
    pricePerKm: 40,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    features: ['AC', 'Comfortable Seats', 'PA System', 'Luggage Bay', 'GPS'],
    bestFor: 'School trips & office outings',
    description: 'Perfect for corporate teams and school groups. Professional driver, comfortable seating, and ample storage.',
    destinations: ['Jaipur', 'Agra', 'Chandigarh', 'Delhi NCR'],
  },
  {
    id: 'coach-bus',
    name: 'Coach Bus',
    category: ['buses', 'group'],
    capacity: '30–45 Passengers',
    luggage: '20+ Bags',
    ac: true,
    pricePerKm: 50,
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80',
    features: ['AC', 'Reclining Seats', 'Entertainment System', 'Luggage Bay', 'GPS', 'PA System'],
    bestFor: 'Large group tours',
    description: 'Full-sized coach for large delegations, tour groups, and corporate events. Professional and punctual.',
    destinations: ['Jaipur', 'Agra', 'Haridwar', 'Chandigarh', 'Delhi NCR'],
  },
  {
    id: 'luxury-bus',
    name: 'Luxury Bus',
    category: ['buses', 'luxury'],
    capacity: '35–45 Passengers',
    luggage: '20+ Bags',
    ac: true,
    pricePerKm: 60,
    image: 'https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?w=800&q=80',
    features: ['Premium AC', 'Sleeper/Airline Seats', 'WiFi', 'Pantry', 'Entertainment', 'GPS'],
    bestFor: 'Premium group & wedding travel',
    description: 'The pinnacle of group travel. Executive seating, in-bus entertainment, and WiFi for the most discerning groups.',
    destinations: ['Jaipur', 'Agra', 'Chandigarh', 'Manali'],
    badge: 'Premium Fleet',
  },
];

export const filterCategories = [
  { id: 'all', label: 'All Vehicles' },
  { id: 'budget', label: 'Budget' },
  { id: 'family', label: 'Family' },
  { id: 'suv', label: 'SUV' },
  { id: 'luxury', label: 'Luxury' },
  { id: 'group', label: 'Group Travel' },
  { id: 'buses', label: 'Buses' },
];
